### ISSUE TITLE
The KeyError encountered when building from source directly in a conda environment.

### ISSUE THREAD

**Issue by DMCXE** [zhisong/pyoculus#12]
In conda environment with numpy=2.2.0 python=3.10.15 setuptools=59.8.0, building from source directly in a conda environment using
 `python setup.pu build_ext` . Fisrtly raise an error about 
```
  from numpy.distutils.fcompiler import get_default_fcompiler
WARN: Could not locate executable armflang
```
At the end raise an error
```
                Constructing F90 module support for "specbasefn"...
            Constructing wrapper function "specbasefn.get_cheby"...
              cheby = get_cheby(lss,lrad)
            Constructing wrapper function "specbasefn.get_cheby_d2"...
              cheby = get_cheby_d2(lss,lrad)
            Constructing wrapper function "specbasefn.get_zernike"...
              zernike = get_zernike(r,lrad,mpol)
            Constructing wrapper function "specbasefn.get_zernike_d2"...
              zernike = get_zernike_d2(r,lrad,mpol)
            Constructing wrapper function "specbasefn.get_zernike_rm"...
              zernike = get_zernike_rm(r,lrad,mpol)
                Constructing F90 module support for "speccoords"...
            Constructing wrapper function "speccoords.get_xyz"...
getctype: No C-type found in "{}", assuming void.
getctype: No C-type found in "{}", assuming void.
getctype: No C-type found in "{}", assuming void.
Traceback (most recent call last):
  File "/public/home/dmcxe/Codes/conda_simsopt/1227/pyoculus/setup.py", line 34, in <module>
    setup(
  File "/public/home/dmcxe/miniconda3/envs/simsall/lib/python3.10/site-packages/numpy/distutils/core.py", line 169, in setup
    return old_setup(**new_attr)
  File "/public/home/dmcxe/miniconda3/envs/simsall/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/public/home/dmcxe/miniconda3/envs/simsall/lib/python3.10/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/public/home/dmcxe/miniconda3/envs/simsall/lib/python3.10/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/public/home/dmcxe/miniconda3/envs/simsall/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/public/home/dmcxe/miniconda3/envs/simsall/lib/python3.10/site-packages/numpy/distutils/command/build_ext.py", line 101, in run
    self.run_command('build_src')
  File "/public/home/dmcxe/miniconda3/envs/simsall/lib/python3.10/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/public/home/dmcxe/miniconda3/envs/simsall/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/public/home/dmcxe/miniconda3/envs/simsall/lib/python3.10/site-packages/numpy/distutils/command/build_src.py", line 144, in run
    self.build_sources()
  File "/public/home/dmcxe/miniconda3/envs/simsall/lib/python3.10/site-packages/numpy/distutils/command/build_src.py", line 161, in build_sources
    self.build_extension_sources(ext)
  File "/public/home/dmcxe/miniconda3/envs/simsall/lib/python3.10/site-packages/numpy/distutils/command/build_src.py", line 321, in build_extension_sources
    sources = self.f2py_sources(sources, ext)
  File "/public/home/dmcxe/miniconda3/envs/simsall/lib/python3.10/site-packages/numpy/distutils/command/build_src.py", line 562, in f2py_sources
    f2py2e.run_main(f2py_options + ['--lower',
  File "/public/home/dmcxe/miniconda3/envs/simsall/lib/python3.10/site-packages/numpy/f2py/f2py2e.py", line 507, in run_main
    ret = buildmodules(postlist)
  File "/public/home/dmcxe/miniconda3/envs/simsall/lib/python3.10/site-packages/numpy/f2py/f2py2e.py", line 412, in buildmodules
    dict_append(ret[name], rules.buildmodule(module, um))
  File "/public/home/dmcxe/miniconda3/envs/simsall/lib/python3.10/site-packages/numpy/f2py/rules.py", line 1317, in buildmodule
    mr, wrap = f90mod_rules.buildhooks(m)
  File "/public/home/dmcxe/miniconda3/envs/simsall/lib/python3.10/site-packages/numpy/f2py/f90mod_rules.py", line 198, in buildhooks
    api, wrap = rules.buildapi(b)
  File "/public/home/dmcxe/miniconda3/envs/simsall/lib/python3.10/site-packages/numpy/f2py/rules.py", line 1478, in buildapi
    vrd = capi_maps.sign2map(a, var[a])
  File "/public/home/dmcxe/miniconda3/envs/simsall/lib/python3.10/site-packages/numpy/f2py/capi_maps.py", line 583, in sign2map
    ret['pydocsign'], ret['pydocsignout'] = getpydocsign(a, var)
  File "/public/home/dmcxe/miniconda3/envs/simsall/lib/python3.10/site-packages/numpy/f2py/capi_maps.py", line 377, in getpydocsign
    sig = '%s : %s %s%s' % (a, opt, c2py_map[ctype], init)
KeyError: 'void'
```
Is this problem due to the environment configuration or the toolchain? On my local machine, I can directly install pyoculus via pip install pyoculus, but I’m encountering this issue in the current environment.

**Comment by DMCXE** [comment]
when setting setuptools=64, then using pip install pyoculus
Collecting pyoculus
  Using cached pyoculus-0.3.1.tar.gz (844 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "/home/dmcxe/miniconda3/envs/voxels/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/dmcxe/miniconda3/envs/voxels/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/dmcxe/miniconda3/envs/voxels/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-zsddgbbp/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/tmp/pip-build-env-zsddgbbp/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-zsddgbbp/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 2, in <module>
        File "/tmp/pip-build-env-zsddgbbp/overlay/lib/python3.9/site-packages/numpy/distutils/core.py", line 24, in <module>
          from numpy.distutils.command import config, config_compiler, \
        File "/tmp/pip-build-env-zsddgbbp/overlay/lib/python3.9/site-packages/numpy/distutils/command/config.py", line 19, in <module>
          from numpy.distutils.mingw32ccompiler import generate_manifest
        File "/tmp/pip-build-env-zsddgbbp/overlay/lib/python3.9/site-packages/numpy/distutils/mingw32ccompiler.py", line 28, in <module>
          from distutils.msvccompiler import get_build_version as get_build_msvc_version
      ModuleNotFoundError: No module named 'distutils.msvccompiler'

**Comment by smiet** [comment]
Thank you for the feedback, sorry that the build is currently not working. 

This is due to the changes in the python build system and C-API that came with numpy 2.0, and we are working on a fix. 

Could you try to check out the meson-build branch and report of it works for you (and your OS, numpy version and other relevant information)?

(Meson does not yet fully support F2py compiled python code, so I had to do a bit of a hack, and want to test it before merging it into main)

**Comment by DMCXE** [comment]
Thank you for your response and for your work on this build.

(Actually, I tried building with my own meson.build file before asking, but I couldn't resolve the dependencies between the Fortran code. The branch you recommended seems to solve this issue.) When I build using Meson `meson compile -C builddir`, the issue persists and seems related to something with kind_map, which causes the build to fail. The error message is identical to the one I encountered when running `python setup.py build_ext`, which is:
```
...
sig = '%s : %s %s%s' % (a, opt, c2py_map[ctype], init)
KeyError: 'void'
...
```
I’m currently using Python 3.10, NumPy 2.2, and setuptools=59, all within a Conda virtual environment, and I have successfully built Python wrappers for vmec, spec, etc.

**Comment by smiet** [comment]
The error originates deep from within F2PY/ C-API in handling the construction of the interface. 

I don't think this is a bug in the pyoculus, rather in the newest release of numpy/F2PY. Can you downgrade to numpy 2.0.0 and try again? Or check if other projects encounter similar errors with numpy 2.2?

 (

**Comment by DMCXE** [comment]
Following your suggestion, I downgraded NumPy to version 2.0.0 and successfully built pyoculus using commands like the following:
```
meson setup builddir
meson compile -C builddir
meson install -C builddir
```
However, I had to comment out the metadata-related sections in `__init__`  to make this work. Directly using `pip install --user . ` still does not work, likely due to environment-related issues on the operating system (the error is the same as previously reported).

The system with the issue is a CentOS Linux running on a commercial computing cluster. At least the problem is resolved for now, but I’ll need some time to understand the differences causing these issues. Thank you so much for your help!

**Comment by smiet** [comment]
Issue fixed with new meson build implemented in  #8
